// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYEHepoiGEw6l8gn3_sXKW2n-BqFFBnl4',
    appId: '1:626089529031:web:a611180be33ba5c314b8e2',
    messagingSenderId: '626089529031',
    projectId: 'delivery-test-a0bff',
    authDomain: 'delivery-test-a0bff.firebaseapp.com',
    storageBucket: 'delivery-test-a0bff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg8b6WI9h_qCYZDUn6EBQR5s11JMFaY0U',
    appId: '1:626089529031:android:1e13bc94cb14451514b8e2',
    messagingSenderId: '626089529031',
    projectId: 'delivery-test-a0bff',
    storageBucket: 'delivery-test-a0bff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp7iJNYuGVTXYoYj5vhSBdB8w2yDZjhkA',
    appId: '1:626089529031:ios:74006d44a15402d414b8e2',
    messagingSenderId: '626089529031',
    projectId: 'delivery-test-a0bff',
    storageBucket: 'delivery-test-a0bff.firebasestorage.app',
    iosBundleId: 'c',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYEHepoiGEw6l8gn3_sXKW2n-BqFFBnl4',
    appId: '1:626089529031:web:fc14c0df75b9141414b8e2',
    messagingSenderId: '626089529031',
    projectId: 'delivery-test-a0bff',
    authDomain: 'delivery-test-a0bff.firebaseapp.com',
    storageBucket: 'delivery-test-a0bff.firebasestorage.app',
  );
}
