// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCoWXYO_5393mVqeE0HHIuIhicjmx8qQs',
    appId: '1:185358176919:web:b6d298e2cf25ed6b678fd2',
    messagingSenderId: '185358176919',
    projectId: 'mypocketerp',
    authDomain: 'mypocketerp.firebaseapp.com',
    storageBucket: 'mypocketerp.firebasestorage.app',
    measurementId: 'G-5F7DP3WFM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbrK8xrc7OLWk3G135ujQXEtdTpX8VEG0',
    appId: '1:185358176919:android:8ab139d2fd39b7c5678fd2',
    messagingSenderId: '185358176919',
    projectId: 'mypocketerp',
    storageBucket: 'mypocketerp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLTWclnCVLwVOXlhJply0iRtXbVJ-rOPE',
    appId: '1:185358176919:ios:3da806fd75e38912678fd2',
    messagingSenderId: '185358176919',
    projectId: 'mypocketerp',
    storageBucket: 'mypocketerp.firebasestorage.app',
    androidClientId: '185358176919-b926q5a38cqvrrjro5msbc49l144dnj4.apps.googleusercontent.com',
    iosClientId: '185358176919-nc4nguioqckf5atjdubi42fv8igbjqdn.apps.googleusercontent.com',
    iosBundleId: 'con.mypocket.sales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCoWXYO_5393mVqeE0HHIuIhicjmx8qQs',
    appId: '1:185358176919:web:0390e1c559fefb03678fd2',
    messagingSenderId: '185358176919',
    projectId: 'mypocketerp',
    authDomain: 'mypocketerp.firebaseapp.com',
    storageBucket: 'mypocketerp.firebasestorage.app',
    measurementId: 'G-QSKPL7R224',
  );

}